### ISSUE TITLE
Propose to data

### ISSUE THREAD

**Issue by MindSpaceMan** [SymfonyCasts/api-platform3#16]
Hi - there is good source to describe api platform subrecource : https://api-platform.com/docs/core/subresources/
as in example from working :

```php
#[ApiResource(
    uriTemplate: '/entity/{id}/reviews.{_format}',
    operations: [new GetCollection(
    )],
    uriVariables: [
        'id' => new Link(fromProperty: 'reviews', fromClass: Review::class)
    ]
)]
```

**Comment by MindSpaceMan** [comment]
Have a good day team - wish you grateful work ))) 💯

**Comment by weaverryan** [comment]
Thanks for this! We DO have an example like this that will be in the Subresources chapter - but thank you for posting and double-checking that we have it :). Subresources are SO much nicer now in API Platform 3.
